#!/usr/bin/env python
from trident.gene_extractor import extract_gene

if __name__ == "__main__":
    from sys import argv,stdout
    from getopt import getopt
    
    # defaults
    output = stdout
    start_loc = 0
    length = 70
    header = ">GENE"
    
    # getopt
    short_opts = "h:n:o:s:"
    long_opts = ["header=", "length=", "output=","start="]
    (opts, args) = getopt(argv[1:],short_opts,long_opts)
        
    if len(args) != 1:
        print("Usage: gene_extractor [-h header] [-s start loc] [-n length] [-o output] <input>")
        exit(1)
    
    for (opt, optarg) in opts:
        while opt[0] == "-":
            opt = opt[1:]
        if opt in ["h","header"]:
            header = optarg
        elif opt in ["n","length"]:
            length = int(optarg)
        elif opt in ["o","output"]:
            output = open(optarg,"w")
        elif opt in ["s","start"]:
            start_loc = int(optarg)
        else:
            print("Unknown flag: %s" % opt)
            exit(1)
        
    infile = open(args[0],"r")
            
    for line in infile:
        if line.strip()[0] == ">":
            break
    output.write("%s\n" % header)
    extract_gene(infile,output,start_loc,length)
