#!/usr/bin/env python

from sys import argv,stdout,stdin
from getopt import getopt,GetoptError
import trident.parser

HELP_WARNING = "For help, run energy_score_mapper --help"
def print_usage():
    print("Usage: energy_score_mapper [-o output] [-i input]")
    print("Options:")
    print("-i, --input\tSpecify input file. Default: Standard Input")
    print("-o, --output\tSpecify output file. Default: Standard Output")
    

short_opts = "hi:o:"
long_opts = ["help","input=","output="]
try:
    (opts,args) = getopt(argv[1:],short_opts,long_opts)
except GetoptError as ge:
    print(ge.msg)
    print(HELP_WARNING)
    exit(1)

infile = stdin
outfile = stdout
for (opt,optarg) in opts:
    while opt[0] == '-':
        opt = opt[1:]
    if opt in ["h","help"]:
        print_usage()
        exit(0)
    elif opt in ["i","input"]:
        infile = open(optarg,"r")
    elif opt in ["o","output"]:
        outfile = open(optarg,"w")
    else:
        print("Unknown flag: %s" % opt)
        print(HELP_WARNING)
        exit(1)
        
parser = trident.parser.Parser(infile)
for hit in parser:
    energy = float(hit['energy'])
    score = hit['score']
    outfile.write("%0.1f:%s\t1\n" % (energy,score))
