#!/usr/bin/env python 
"""
Reads an energy-score summary table and generates a Linear Piecewise Interpolator Function.
"""
from sys import argv
import pickle
from trident.classify import create_linear_interpolator
from getopt import getopt

def print_usage():
    print("Usage: interpolate [-o output] <input file>")
    print("-o, --output\tOutput file in which the interpolator function is saved.")
    
short_opts = "ho:"
long_opts = ["help","output="]

(opts,args) = getopt(argv[1:],short_opts,long_opts)

funct_filename = "interpolator.sav"
infilename = None
for (opt,optarg) in opts:
    while opt[0] == '-':
        opt = opt[1:]
    if opt in ["h","help"]:
        print_usage()
        exit(0)
    elif opt in ["o","output"]:
        funct_filename = optarg
        
if len(args) != 1:
    raise Exception("Invalid number of arguments. Only need an input filename")
infilename = args[0]

# Interpolate
print("Interpolating")
interpolator = create_linear_interpolator(infilename)
interpolator.save(funct_filename)
