#!/usr/bin/env python
"""
Crawls an input file and validates the energy based on the sequence.

Uses the trident.core python extension
"""

def print_usage():
    print("Usage: validate_energies <output file>")

def main():
    from sys import stdin,argv
    from trident.validate_energies import validate_file

    infile = stdin

    if len(argv) == 2 and argv[1] not in ["-h","--help"]:
        infile = open(argv[1],"r")
    else:
        print_usage()
        exit(1)

    validate_file(infile)



if __name__ == "__main__":
    main()
    